#!/usr/bin/env bash
# 05-stack-config.sh — generate the compose project under $DATA_MOUNT/stack
# from the templates in stack/. Renders docker-compose.yml, Caddyfile,
# litellm-config.yaml and .env according to config.env.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"
announce_script "05-stack-config.sh"

require_root
require_done 04-nvidia-toolkit
load_config

STACK_DIR="$DATA_MOUNT/stack"
mkdir -p "$STACK_DIR" "$STACK_DIR/caddy" "$STACK_DIR/pgdata"

step "Generating secrets where missing"
if [ -z "${LITELLM_MASTER_KEY:-}" ]; then
    LITELLM_MASTER_KEY="sk-$(openssl rand -hex 32)"
    write_config LITELLM_MASTER_KEY "$LITELLM_MASTER_KEY"
fi
if [ -z "${POSTGRES_PASSWORD:-}" ]; then
    POSTGRES_PASSWORD="$(openssl rand -hex 16)"
    write_config POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
fi

# Defaults for variables introduced after an older config.env was written
ENABLE_VLLM2="${ENABLE_VLLM2:-no}"
VLLM_EXTRA_ARGS="${VLLM_EXTRA_ARGS:-}"
VLLM2_MODEL="${VLLM2_MODEL:-}"
VLLM2_SERVED_NAME="${VLLM2_SERVED_NAME:-}"
VLLM2_GPU_MEM_UTIL="${VLLM2_GPU_MEM_UTIL:-0.90}"
VLLM2_MAX_MODEL_LEN="${VLLM2_MAX_MODEL_LEN:-8192}"
VLLM2_EXTRA_ARGS="${VLLM2_EXTRA_ARGS:-}"

# Compose profiles
PROFILES=""
[ "$ENABLE_OLLAMA" = "yes" ] && PROFILES="${PROFILES}ollama,"
[ "$ENABLE_VLLM" = "yes" ]   && PROFILES="${PROFILES}vllm,"
[ "$ENABLE_VLLM2" = "yes" ]  && PROFILES="${PROFILES}vllm2,"
PROFILES="${PROFILES%,}"

step "Writing $STACK_DIR/.env"
cat > "$STACK_DIR/.env" <<EOF
# Generated by 05-stack-config.sh — DO NOT edit by hand, re-run the script.
COMPOSE_PROFILES=$PROFILES

DOMAIN=$DOMAIN
ACME_EMAIL=$ACME_EMAIL
ALLOWED_IPS=$ALLOWED_IPS

LITELLM_IMAGE=$LITELLM_IMAGE
LITELLM_MASTER_KEY=$LITELLM_MASTER_KEY
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
DATABASE_URL=postgresql://litellm:$POSTGRES_PASSWORD@db:5432/litellm

OLLAMA_IMAGE_TAG=$OLLAMA_IMAGE_TAG
OLLAMA_KEEP_ALIVE=$OLLAMA_KEEP_ALIVE
OLLAMA_MAX_LOADED_MODELS=$OLLAMA_MAX_LOADED_MODELS
OLLAMA_NUM_PARALLEL=$OLLAMA_NUM_PARALLEL

VLLM_IMAGE_TAG=$VLLM_IMAGE_TAG
VLLM_MODEL=$VLLM_MODEL
VLLM_SERVED_NAME=$VLLM_SERVED_NAME
VLLM_GPU_MEM_UTIL=$VLLM_GPU_MEM_UTIL
VLLM_MAX_MODEL_LEN=$VLLM_MAX_MODEL_LEN
VLLM_EXTRA_ARGS=$VLLM_EXTRA_ARGS
HF_TOKEN=$HF_TOKEN

VLLM2_MODEL=$VLLM2_MODEL
VLLM2_SERVED_NAME=$VLLM2_SERVED_NAME
VLLM2_GPU_MEM_UTIL=$VLLM2_GPU_MEM_UTIL
VLLM2_MAX_MODEL_LEN=$VLLM2_MAX_MODEL_LEN
VLLM2_EXTRA_ARGS=$VLLM2_EXTRA_ARGS
EOF
chmod 600 "$STACK_DIR/.env"

step "Rendering templates"
TPL="$SCRIPT_DIR/../stack"
# The templates are copied verbatim: ${VAR} in docker-compose.yml is resolved
# by docker compose from .env, and {$VAR} in the Caddyfile is resolved by
# Caddy at startup from the container environment.
cp "$TPL/docker-compose.yml.tmpl"  "$STACK_DIR/docker-compose.yml"
cp "$TPL/Caddyfile.tmpl"           "$STACK_DIR/caddy/Caddyfile"

# Render litellm config with enabled engines only
{
    cat "$TPL/litellm-config.header.tmpl"
    if [ "$ENABLE_OLLAMA" = "yes" ]; then
        for tag in $OLLAMA_MODELS_PULL; do
            short="$(echo "$tag" | tr ':' '-' | tr '[:upper:]' '[:lower:]')"
            cat <<EOF
  - model_name: $short
    litellm_params:
      model: ollama/$tag
      api_base: http://ollama:11434
EOF
        done
    fi
    if [ "$ENABLE_VLLM" = "yes" ]; then
        cat <<EOF
  - model_name: $VLLM_SERVED_NAME
    litellm_params:
      model: openai/$VLLM_SERVED_NAME
      api_base: http://vllm:8000/v1
      api_key: dummy
EOF
    fi
    if [ "$ENABLE_VLLM2" = "yes" ]; then
        cat <<EOF
  - model_name: $VLLM2_SERVED_NAME
    litellm_params:
      model: openai/$VLLM2_SERVED_NAME
      api_base: http://vllm2:8000/v1
      api_key: dummy
EOF
    fi
} > "$STACK_DIR/litellm-config.yaml"

chmod 600 "$STACK_DIR/litellm-config.yaml"

step "Installing DB backup script + nightly cron"
cp "$TPL/backup-db.sh" "$STACK_DIR/backup-db.sh"
chmod 755 "$STACK_DIR/backup-db.sh"
cat > /etc/cron.d/llm-db-backup <<EOF
# Nightly LiteLLM PostgreSQL dump — generated by 05-stack-config.sh
MAILTO=""
17 3 * * * root $STACK_DIR/backup-db.sh >> /var/log/llm-db-backup.log 2>&1
EOF
chmod 644 /etc/cron.d/llm-db-backup

chown -R root:root "$STACK_DIR"

step "Summary"
ls -la "$STACK_DIR"
echo
info "Master key (also stored in $CONFIG_FILE and $STACK_DIR/.env):"
echo "   $LITELLM_MASTER_KEY"
warn "Save the master key in your password manager."

mark_done 05-stack-config
ok "Next: sudo scripts/06-pull-models.sh"
